version: '2'

services:

    # Web Service
    domserver:
        image: domjudge/domserver
        volumes:
           - "/var/run/mysqld:/var/run/mysqld"
           - "/var/www/apps/domserver/submissions:/opt/domjudge/domserver/submissions"
        environment:
           - MYSQL_HOST=172.17.0.1
           - MYSQL_DATABASE=domjudge
           - MYSQL_USER=judge
           - MYSQL_PASSWORD=ou4Geosh
        ports:
         - "4321:80"
        network_mode: bridge
        restart: always

    # Judgehosts Service
    judgehost:
        image: domjudge/judgehost
        links:
           - domserver
        volumes:
           - "/sys/fs/cgroup/cpuset/domjudge:/cgroup/cpuset/domjudge"
           - "/sys/fs/cgroup/memory/domjudge:/cgroup/memory/domjudge"
           - "/dev:/dev"
           - "/var/www/apps/domserver/log:/opt/domjudge/judgehost/log"
           - "/var/www/apps/domserver/judgings:/opt/domjudge/judgehost/judgings"
        environment:
           - API_URL=http://domserver/api/
           - API_USER=judgehost
           - API_PASSWORD=wePvqmo4U01EIVkHotq5
        privileged: true
        ipc: host
        network_mode: bridge
        restart: always
